model:
  name: "emotion_recognition_v8"
  type: "ONNX"
  detection_path: "${MODELS_DIR}/buffalo_l/det_10g.onnx"
  recognition_path: "${MODELS_DIR}/affectnet_emotion.onnx"
  input_size: [640, 640]  
  recog_input_size: [64, 64]  
  output_classes: 
    - "neutral"
    - "happy"
    - "surprise"
    - "sad"
    - "anger"
    - "disgust"
    - "fear"
    - "contempt"
  threshold: 0.2

detection:
  min_confidence: 0.7
  max_faces: 5
  landmark_points: 5  

tracking:
  decay_rate: 0.95
  buffer_size: 15
  transition_threshold: 0.25
  engagement_threshold: 0.4

augmentation:
  enabled: true
  techniques:
    - "random_brightness"
    - "random_contrast"
    - "horizontal_flip"
  params:
    brightness_range: [0.8, 1.2]
    contrast_range: [0.8, 1.2]